'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import {supabase} from '../lib/supabase'
import schedule from '../data/schedule.json'

const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const TASKS=(r)=>{
 const a=[]; if(r.anki && !/rest/i.test(r.anki)) a.push({type:'Anki',title:r.anki,resource:'Anki'})
 if(r.questions>0)a.push({type:'Questions',title:`${r.questions} science/P-S questions + full review`,resource:r.source})
 if(r.cars>0)a.push({type:'CARS',title:`${r.cars} CARS passage${r.cars>1?'s':''} + review`,resource:/AAMC/i.test(r.source)?'AAMC':'Jack Westin'})
 if(r.content && !/none|rest/i.test(r.content))a.push({type:'Content',title:r.content,resource:'Targeted review'})
 if(!a.length)a.push({type:'Rest',title:'Recovery / rest day',resource:'Recovery'})
 return a
}
export default function Home(){
 const [session,setSession]=useState(null),[authMode,setAuthMode]=useState('login'),[msg,setMsg]=useState(''),[tab,setTab]=useState('Today'),[tasks,setTasks]=useState([]),[days,setDays]=useState([]),[selected,setSelected]=useState(todayISO()),[loading,setLoading]=useState(true),[qlogs,setQlogs]=useState([]),[fls,setFls]=useState([]),[seconds,setSeconds]=useState(50*60),[running,setRunning]=useState(false),[focusMin,setFocusMin]=useState(50),[breakMin,setBreakMin]=useState(10),[timerMode,setTimerMode]=useState('Focus'); const timer=useRef(null)
 const planned=useMemo(()=>schedule.find(x=>x.date===selected)||schedule[0],[selected])
 useEffect(()=>{if(!supabase){setLoading(false);setMsg('Supabase environment variables are missing.');return} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session){seed();loadAll(); const ch=supabase.channel('mcat-sync').on('postgres_changes',{event:'*',schema:'public',table:'daily_tasks',filter:`user_id=eq.${session.user.id}`},()=>loadAll()).subscribe();return()=>supabase.removeChannel(ch)}},[session])
 useEffect(()=>{if(running){timer.current=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);clearInterval(timer.current); if(timerMode==='Focus'){logSession(focusMin);setTimerMode('Break');return breakMin*60}else{setTimerMode('Focus');return focusMin*60}}return s-1}),1000)}return()=>clearInterval(timer.current)},[running,timerMode,focusMin,breakMin])
 async function auth(e){e.preventDefault();setMsg('');const fd=new FormData(e.currentTarget),email=fd.get('email'),password=fd.get('password');let res=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setMsg(res.error?res.error.message:(authMode==='signup'&&!res.data.session?'Check your email to confirm your account.':''))}
 async function seed(){const uid=session.user.id;const {count}=await supabase.from('study_days').select('*',{count:'exact',head:true}).eq('user_id',uid);if(count>0)return; const dayRows=schedule.map(r=>({user_id:uid,study_date:r.date,phase:r.phase,planned_hours:r.hours,is_rest_day:TASKS(r)[0]?.type==='Rest',is_full_length_day:/full.?length|FL/i.test(r.assignment+' '+r.notes)}));const {data:inserted,error}=await supabase.from('study_days').insert(dayRows).select();if(error){setMsg(error.message);return}const map=Object.fromEntries(inserted.map(d=>[d.study_date,d.id]));let taskRows=[];schedule.forEach(r=>TASKS(r).forEach((t,i)=>taskRows.push({user_id:uid,study_day_id:map[r.date],task_date:r.date,task_type:t.type,title:t.title,description:r.assignment,resource:t.resource,estimated_minutes:Math.max(15,Math.round((r.hours*60)/TASKS(r).length)),sort_order:i})));for(let i=0;i<taskRows.length;i+=500)await supabase.from('daily_tasks').insert(taskRows.slice(i,i+500));}
 async function loadAll(){const uid=session.user.id;const [t,d,q,f]=await Promise.all([supabase.from('daily_tasks').select('*').eq('user_id',uid).order('task_date').order('sort_order'),supabase.from('study_days').select('*').eq('user_id',uid).order('study_date'),supabase.from('question_blocks').select('*').eq('user_id',uid).order('question_date',{ascending:false}).limit(100),supabase.from('full_length_scores').select('*').eq('user_id',uid).order('exam_date')]);setTasks(t.data||[]);setDays(d.data||[]);setQlogs(q.data||[]);setFls(f.data||[])}
 async function toggle(t){await supabase.from('daily_tasks').update({completed:!t.completed,completed_at:!t.completed?new Date().toISOString():null}).eq('id',t.id);loadAll()}
 async function logSession(min){if(!session)return;await supabase.from('study_sessions').insert({user_id:session.user.id,session_date:todayISO(),actual_minutes:min,planned_minutes:min,session_type:'focus',ended_at:new Date().toISOString()})}
 async function addQuestions(e){e.preventDefault();const f=new FormData(e.currentTarget),total=+f.get('total'),correct=+f.get('correct');if(correct>total){setMsg('Correct answers cannot exceed total questions.');return}await supabase.from('question_blocks').insert({user_id:session.user.id,question_date:todayISO(),source:f.get('source'),subject:f.get('subject'),total_questions:total,correct_questions:correct,timed:f.get('timed')==='on'});e.currentTarget.reset();loadAll()}
 async function addFL(e){e.preventDefault();const f=new FormData(e.currentTarget);const vals=['cp','cars','bb','ps'].map(k=>+f.get(k));await supabase.from('full_length_scores').insert({user_id:session.user.id,exam_date:f.get('date'),exam_name:f.get('name'),cp_score:vals[0],cars_score:vals[1],bb_score:vals[2],ps_score:vals[3],total_score:vals.reduce((a,b)=>a+b,0)});e.currentTarget.reset();loadAll()}
 if(loading)return <main className="center"><div className="loader"/></main>
 if(!session)return <main className="auth"><div className="authCard"><div className="brand"><span>λ</span><div><h1>MCAT Study Tracker</h1><p>Built for the long game.</p></div></div><h2>{authMode==='login'?'Welcome back':'Create your account'}</h2><form onSubmit={auth}><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" minLength="6" required/><button>{authMode==='login'?'Sign in':'Create account'}</button></form>{msg&&<p className="message">{msg}</p>}<button className="link" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Need an account? Sign up':'Already have an account? Sign in'}</button></div></main>
 const dayTasks=tasks.filter(t=>t.task_date===selected),done=dayTasks.filter(t=>t.completed).length,pct=dayTasks.length?Math.round(done/dayTasks.length*100):0;const allDone=tasks.filter(t=>t.completed).length;const accuracy=qlogs.length?Math.round(qlogs.reduce((a,q)=>a+q.correct_questions,0)/qlogs.reduce((a,q)=>a+q.total_questions,0)*100):0;const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');
 return <main className="shell"><aside><div className="logo">λ <span>MCAT</span></div>{['Today','Calendar','Questions','Full Lengths','Analytics'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<div className="spacer"/><button onClick={()=>supabase.auth.signOut()}>Sign out</button></aside><section className="content"><header><div><p className="eyebrow">{planned?.phase||'MCAT PLAN'}</p><h1>{tab}</h1></div><div className="countdown"><b>{Math.max(0,Math.ceil((new Date('2027-04-17T12:00:00')-new Date())/86400000))}</b><span>days to MCAT</span></div></header>
 {tab==='Today'&&<><div className="hero"><div><p>{new Date(selected+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</p><h2>{planned?.assignment||'Study plan'}</h2><div className="bar"><i style={{width:pct+'%'}}/></div><small>{done} of {dayTasks.length} tasks complete · {planned?.hours||0} planned hours</small></div><div className="ring" style={{'--p':pct}}><b>{pct}%</b></div></div><div className="grid2"><div className="card"><h3>Today’s checklist</h3>{dayTasks.map(t=><label className={'task '+(t.completed?'done':'')} key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>toggle(t)}/><span><b>{t.task_type}</b>{t.title}<small>{t.resource}</small></span></label>)}{!dayTasks.length&&<p>No tasks for this date yet.</p>}</div><div className="card timer"><div className="timerTop"><h3>Pomodoro</h3><select value={focusMin} onChange={e=>{let v=+e.target.value;setFocusMin(v);setBreakMin(v===25?5:10);setSeconds(v*60);setTimerMode('Focus');setRunning(false)}}><option value="25">25 / 5</option><option value="50">50 / 10</option><option value="60">60 / 10</option></select></div><p>{timerMode}</p><strong>{m}:{s}</strong><div className="actions"><button onClick={()=>setRunning(!running)}>{running?'Pause':'Start'}</button><button className="secondary" onClick={()=>{setRunning(false);setTimerMode('Focus');setSeconds(focusMin*60)}}>Reset</button></div></div></div></>}
 {tab==='Calendar'&&<div className="card"><div className="calendarHead"><h3>Study calendar</h3><input type="date" value={selected} min="2026-09-15" max="2027-04-17" onChange={e=>setSelected(e.target.value)}/></div><div className="monthGrid">{schedule.map(r=>{const dt=tasks.filter(t=>t.task_date===r.date),dc=dt.filter(t=>t.completed).length,p=dt.length?dc/dt.length:0;return <button key={r.date} onClick={()=>{setSelected(r.date);setTab('Today')}} className={r.date===todayISO()?'today':''}><span>{fmt(r.date)}</span><b>{r.phase.split('/')[0]}</b><i style={{width:(p*100)+'%'}}/><small>{dc}/{dt.length}</small></button>})}</div></div>}
 {tab==='Questions'&&<div className="grid2"><div className="card"><h3>Log a question block</h3><form className="form" onSubmit={addQuestions}><select name="source"><option>UWorld</option><option>AAMC</option><option>Kaplan</option><option>Jack Westin</option></select><select name="subject"><option>B/B</option><option>C/P</option><option>P/S</option><option>CARS</option></select><input name="total" type="number" min="1" placeholder="Total questions" required/><input name="correct" type="number" min="0" placeholder="Correct" required/><label className="check"><input name="timed" type="checkbox"/> Timed block</label><button>Save block</button></form></div><div className="card"><h3>Recent performance</h3><div className="bigStat">{accuracy}%<small>overall accuracy</small></div>{qlogs.slice(0,8).map(q=><div className="row" key={q.id}><span>{q.source} · {q.subject}</span><b>{q.correct_questions}/{q.total_questions}</b></div>)}</div></div>}
 {tab==='Full Lengths'&&<div className="grid2"><div className="card"><h3>Log full-length</h3><form className="form" onSubmit={addFL}><input name="date" type="date" required/><input name="name" placeholder="Exam name (e.g. AAMC FL 1)" required/><div className="four"><input name="cp" type="number" min="118" max="132" placeholder="C/P" required/><input name="cars" type="number" min="118" max="132" placeholder="CARS" required/><input name="bb" type="number" min="118" max="132" placeholder="B/B" required/><input name="ps" type="number" min="118" max="132" placeholder="P/S" required/></div><button>Save score</button></form></div><div className="card"><h3>Score history</h3>{fls.length?fls.map(f=><div className="score" key={f.id}><div><b>{f.exam_name}</b><small>{fmt(f.exam_date)}</small></div><strong>{f.total_score}</strong></div>):<p>No full-lengths logged yet.</p>}</div></div>}
 {tab==='Analytics'&&<><div className="stats"><div><b>{allDone}</b><span>tasks completed</span></div><div><b>{tasks.length?Math.round(allDone/tasks.length*100):0}%</b><span>plan completed</span></div><div><b>{qlogs.reduce((a,q)=>a+q.total_questions,0)}</b><span>questions logged</span></div><div><b>{accuracy||'—'}</b><span>{accuracy?'% accuracy':'accuracy'}</span></div></div><div className="card"><h3>Phase roadmap</h3>{[['Sep–Oct','Ramp-up + Kaplan/JW'],['Nov–Jan','UWorld-heavy practice'],['Feb–Mar','AAMC official material + FLs'],['April','Final AAMC work + taper']].map((x,i)=><div className="road" key={x[0]}><em>{i+1}</em><div><b>{x[0]}</b><p>{x[1]}</p></div></div>)}</div></>}
 {msg&&<div className="toast">{msg}</div>}</section></main>
}
